Add mask option to measurement Sweep
nulinspiratie/Qcodes pull request #103
Opened 2020-09-19 13:08 UTC by maij

When constructing large measurements that sweep multiple parameters, it may arise that you want to be able to reset a parameter to its original value after performing a sweep, such as with a DC gate scan.
```python
with Measurement('dc_scan') as msmt:
   msmt.mask(DG1, DG1())
   for _ in Sweep(DG1.sweep(0, 1, num=100)):
      # measure something
   msmt.unmask(DG1)
   msmt.mask(DG2, DG2())
   for _ in Sweep(DG2.sweep(0, 1, num=100)):
      # measure something 
   msmt.unmask(DG2)
   # etc.
```
This is quite tedious, manually masking and unmasking parameters before and after each loop. This can also lead to measurements becoming unintentionally dynamic, for example:

```python
with Measurement('nested_dc_scan') as msmt:
   for _ in Sweep(TG.sweep(1.5, 1.8, num=100):
      for _ in Sweep(SPL.sweep(window=200e-3, num=10):
         # measure something

```
One might think that SPL will scan over a 200 mV range from where it's set at the beginning of the experiment, but after each iteration over the TG values, the window will shift as the final setpoint of SPL is 200e-3, and so a new window is generated about this point.

To answer these issues, I've added a simple flag `mask` to the Sweep class, which automatically masks and unmasks parameter values. Other Sweep values (such as a list) will raise a `NotImplementedError`.

--- 

```python
from qcodes.measurement import *
from qcodes.instrument.parameter import Parameter

masked_parameter = Parameter('masked', get_cmd=None, set_cmd=None)
unmasked_parameter = Parameter('unmasked', get_cmd=None, set_cmd=None)

masked_parameter(42)
unmasked_parameter(61)
with Measurement('test_sweep_masking'):
    print(f"before sweep, masked parameter is {masked_parameter()}")
    for _ in Sweep(masked_parameter.sweep(0, 1, num=100), mask=True):
        msmt.measure(masked_parameter)
    print(f"after sweep, masked parameter is {masked_parameter()}")
    for _ in Sweep(np.linspace(1, 100, 34), mask=False):
        msmt.measure(1, name='dummy')
        
    print(f"before sweep, masked parameter is {unmasked_parameter()}")
    for _ in Sweep(unmasked_parameter.sweep(0, 1, num=100), mask=False):
        msmt.measure(unmasked_parameter)
    print(f"after sweep, unmasked parameter is {unmasked_parameter()}")
    
```
Output:
```
before sweep, masked parameter is 42
after sweep, masked parameter is 42
before sweep, masked parameter is 61
after sweep, unmasked parameter is 1.0

```

2020-09-24 22:57 UTC, nulinspiratie commented
Cool addition, I was also thining of adding this. However, one flaw here is that if you exit the loop before reaching StopIteration, it won't actually unmask... So if you add a `break` statement, or an error occurs, the masked value is never unmasked.

There is no easy way around it, the best solution might be to change Sweep from an iterator to a context manager

2020-09-29 11:38 UTC, maij commented
> Cool addition, I was also thining of adding this. However, one flaw here is that if you exit the loop before reaching StopIteration, it won't actually unmask... So if you add a `break` statement, or an error occurs, the masked value is never unmasked.
> 
> There is no easy way around it, the best solution might be to change Sweep from an iterator to a context manager

This is actually fine with exceptions, because the measurement will still unmask all masked parameters when exiting. But it does share the same problem of `break` statements as the measurement stepping out problem. I can't see a clean way of making Sweep a context manager though... it would require bulking out the measurement code quite a bit.

2020-09-30 00:13 UTC, nulinspiratie commented
Ah I think I found a way! 
Whenever a value is masked, it will be unmasked when the measurement steps out of the relevant dimension.
So basically:

```Python
with Measurement('msmt') as msmt
    p = Parameter(initial_value=1)
    for k in Sweep(range(4)):
        msmt.mask(p, 2)
        # Do actions here
    
    print(p())  # Returns 1, since we exited the sweep
```

2020-09-30 00:38 UTC, maij commented
Are you suggesting changing the code to unmask when `msmt.step_out` is called? It doesn't currently have that functionality.

This also doesn't work when you want to mask the swept parameter, because once you enter the loop the value of the parameter is changed, and so you lose the original value. I suppose you could do:

```python
with Measurement('msmt') as msmt:
    p = Parameter(initial_value=1, set_cmd=None)
    original_value = p()
    for k in Sweep(p[range(4)]):
        msmt.mask(p, original_value)
        # Do actions here
    
    print(p())  # Prints 1
```

But then you might as well use the original method of manually masking/unmasking before and after the loop.

2020-10-21 03:46 UTC, nulinspiratie commented
Ahhh I went back to this PR, and I realized that I misunderstood the functionality of it. I think part of the reason for my confusion is that in my mind masking is meant to temporarily change a variable for the duriation of a measurement, while in this case it's more that the value should be reset to its original after the Sweep is finished.

I understand that the underlying code is the same in both cases (i.e. masking), but I think it would be a good idea to choose a kwarg other than `mask`, something like `revert=True` or `reset=True`. What do you think?

In any case, I also think that it's worthwhile to add the unmasking idea I mentioned above, namely dependent on stepping out of a loop.

2021-01-11 02:42 UTC, RostyslavSavytskyy commented
Sorry for being late to the party, but we are already using msmt.revert(N=...) to revert the indexes in the measurement loops. Although you are implementing the flag as an argument of the Sweep(), I would still suggest renaming it to "reset" or something less overlapping.

2021-01-27 22:02 UTC, maij commented
@RostyslavSavytskyy @nulinspiratie 

I've gone with kwarg `restore` for this option now. Final review requested.

2021-01-29 06:11 UTC, RostyslavSavytskyy requested changes
missed one more renaming

2021-01-29 06:11 UTC, RostyslavSavytskyy commented on qcodes/measurement.py
> +            if self.revert:
missed one more renaming

2021-01-31 00:43 UTC, RostyslavSavytskyy approved these changes

2021-01-31 00:44 UTC, RostyslavSavytskyy commented
Looks good to me, but haven't tested myself yet

2021-02-06 12:04 UTC, merged